// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvjG5BcRHLBegcuobQ1F7SHQjlcDA_LcA',
    appId: '1:238362214629:web:6cbddff0e4a1b37d23140c',
    messagingSenderId: '238362214629',
    projectId: 'jp-miso-guesong',
    authDomain: 'jp-miso-guesong.firebaseapp.com',
    storageBucket: 'jp-miso-guesong.appspot.com',
    measurementId: 'G-P0GVY346Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfKbfWHc4zoOXxMKNS65XtrYtz_OE3M4c',
    appId: '1:238362214629:android:68055378e8ef512a23140c',
    messagingSenderId: '238362214629',
    projectId: 'jp-miso-guesong',
    storageBucket: 'jp-miso-guesong.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMFHDAMb7vpN2ggzmx5DECgXsxJP1soP4',
    appId: '1:238362214629:ios:3de168559c7106d923140c',
    messagingSenderId: '238362214629',
    projectId: 'jp-miso-guesong',
    storageBucket: 'jp-miso-guesong.appspot.com',
    iosBundleId: 'com.example.guessTheSong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMFHDAMb7vpN2ggzmx5DECgXsxJP1soP4',
    appId: '1:238362214629:ios:3de168559c7106d923140c',
    messagingSenderId: '238362214629',
    projectId: 'jp-miso-guesong',
    storageBucket: 'jp-miso-guesong.appspot.com',
    iosBundleId: 'com.example.guessTheSong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvjG5BcRHLBegcuobQ1F7SHQjlcDA_LcA',
    appId: '1:238362214629:web:0a4de8512e0f998e23140c',
    messagingSenderId: '238362214629',
    projectId: 'jp-miso-guesong',
    authDomain: 'jp-miso-guesong.firebaseapp.com',
    storageBucket: 'jp-miso-guesong.appspot.com',
    measurementId: 'G-GGLWJXGR7C',
  );
}
